


spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/identity
    username: postgres
    password: KHANH2005t
    driver: postgresql


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true



#  datasource:
#    url: jdbc:postgresql://localhost:5433/identity
#    username: postgres
#    password: KHANH2005t
